services:
  mysql:
    image: mysql:8.4
    container_name: nexo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: tutorias
      MYSQL_DATABASE: nexo
    ports:
      - "3306:3306"
    volumes:
      - nexo_mysql:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

volumes:
  nexo_mysql:
